version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/ktbartholomew/github-proxy
    steps:
      - checkout
      - run: go build ./...
workflows:
  version: 2
  workflow:
    jobs:
      - build
