apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: github-proxy
  namespace: keithbartholomew
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: github-proxy
    spec:
      containers:
      - name: github-proxy
        image: quay.io/ktbartholomew/github-proxy
        env:
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: github-proxy
              key: github_client
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: github-proxy
              key: github_secret
        ports:
        - containerPort: 8080
