apiVersion: v1
kind: Service
metadata:
  name: github-proxy
  namespace: keithbartholomew
spec:
  selector:
    app: github-proxy
  ports:
  - port: 80
    targetPort: 8080
    name: http
    protocol: TCP
  type: ClusterIP
